default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: jwines
  host: localhost
  encoding: utf8
  port: 5432

development:
  <<: *default
  database: instrumento_dev

test:
  <<: *default
  database: instrumento_test