user: deploy
group: deploy
pid: /home/deploy/apps/instrumento/tmp/pids/thin.pid
timeout: 30
wait: 30
log: /home/deploy/apps/instrumento/log/thin.log
max_conns: 1024
require: []
threaded: true
no-epoll: true
environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
socket: /home/deploy/apps/instrumento/sockets/thin.sock